### ISSUE TITLE
Update README: Roadmap

### ISSUE THREAD

**Issue by georgiakirkpatrick** [georgiakirkpatrick/veronaut-products-api#15]
Roadmap

(Below text is from https://mozillascience.github.io/working-open-workshop/roadmapping/)

When you're starting on an open source project, it's important to record what your community (this might just be you at the beginning) decides to work on! A roadmap organizes the tasks that nees to be done on a project around milestones. This helps potential contributors understand the current status of your poject and where it's going next.

A roadmap can also express your vision for the project. Make sure you clearly state why you are implementing certain things to get people excited about joining.

This can be as simple as a collection of issues in your issue tracker, or a detailed timeline complete with milestones. It's up to you to choose what works best for your community!

This section organizes tasks needed to complete your project around milestones, mapping out what you're working on now and where it's going next. This can be as simple as a list of issues in your issue tracker.

Depending on your project, milestones can vary from development goals to events. Here are some milestones you can use:

Project Status Goals

Are you working to implement your MVP (minimum viable product) or a specific feature? Your milestones can be completing a feature or a release.

examples: Get your project on Collaborate, build an MVP

Dates

If you have deadlines or a set time to work on this project, use this as a milestone!

Events

If you'll be sprinting or demoing your project at an event, it's helpful to know what you'll need to complete before and during the event.

examples: Mozilla Science Lab Global Sprint prep work, MozFest sprint tasks

Short, Medium & Long Term

When working with volunteers, it can be difficult to set hard deadlines. When unsure, you can use short, medium and long term milestones.

Short term - things you are working on now

Medium term - things contributors can start working on that is not currently being worked on

Long term - you can describe where your project is going here

- [ ]  Add some of the challenges I faced with the app.
- [ ] 
- [ ]  Add features I hope to implement in the future. Link to "Issues" as applicable.
- [ ] 
- [ ]  Pick Milestones
- [ ] 
- [ ]  Write a milestone for each task
- [ ] 
- [ ]  Create an issue for each task. Take time to describe the task along with why you are doing this task. This will strengthen the vision for your project and help others get involved.

 Link to these issues in your Roadmap under each milestone.

Tips for issues: Include as much context and help as possible! Add links, mention specific people involved by their username. Articulate the problem or idea along with solutions and next steps.
Link to these issues in your Roadmap under each milestone. Congrats! You now have a Roadmap with tasks.
